name: .NET WASM CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0'

    - name: Restore dependencies
      working-directory: ./BlazorProvaThiago 
      run: dotnet restore

    - name: Build project
      working-directory: ./BlazorProvaThiago 
      run: dotnet publish -c Release -o build
